version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bankcards_postgres
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankcardsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: yourappimage:latest  # Или можешь использовать Dockerfile
    container_name: bankcards_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcardsdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    command: ["java", "-jar", "/app/bankcards-0.0.1-SNAPSHOT.jar"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: bankcards_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
