debug: true
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
# Безопасность
security:
  jwt:
    secret-key: "MySuperSecretKeyMySuperSecretKey123456"
    expiration: 3600000

#Swagger UI (SpringDoc)
springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  default-produces-media-type: application/json

